### ISSUE TITLE
how to box select, zoom in and out the chart?

### ISSUE THREAD

**Issue by xinsuinizhuan** [scottgshin/ChartCtrl#11]
I want to rectangle the chart, and zoom in and out it?how to do?

**Comment by scottgshin** [comment]
Search the _An MFC Chart Control with Enhanced User Interface - CodeProject.pdf_ document found in the project for zoom. There is a section on how to zoom in, in the Y direction and separately in the X direction.  The functionality for drawing a box for a zoom is not currently built in. If you want to add that functionality, I would be willing to add it.

Here is some of the information on how to zoom:
**There are two ways to zoom in the container:** using the mouse and from the popup menu. To zoom in horizontally using the mouse, left click on the container with the SHIFT key is depressed. A vertical line will show you the first of the X-boundaries of a zoom extent. The second left click with the depressed SHIFT key will show you the other boundary of the zoom extent. On LBUTTONUP, the X-axis of the container will be changed to the new X-extent, and the container window will be updated. The data label position will be adjusted according to the new position of the selected X-coordinate. The data label is hidden if the selected X went out of view. To horizontally zoom from the popup menu, select the "Zoom In X" menu item from the "Zoom/Move" submenu. The new X-axis extent will be 80% of the old extent. The container saves the values of the previous boundaries of the X-axis to allow undoing the zooming. 
**To zoom in vertically** you also can use the mouse or the context menu. With the mouse you start with the depressed SHIFT key and double left click. A vertical line will be replaced by a horizontal line along a first vertical zoom boundary. The second left click (just left click, not the double left click) will display the second vertical boundary. Release the mouse left button, and the new, zoomed in vertical extent will be displayed. To use the popup menu, use the "Zoom In Y" menu item from the "Zoom/Move" submenu. Again, there will be 80% of the old Y-extent. The data label content will be synchronized with the picture in the container's window. There is no zooming on the container's window if there is no visible data points: the X and Y-extensions will not change. The container saves the values of the previous boundaries of the Y-axis to allow undoing the zooming.
