### ISSUE TITLE
Unassigned  variable

### ISSUE THREAD

**Issue by gry321** [scottgshin/ChartCtrl#13]
In ChartCtrl.h file, "m_pAxes" init at 538 lines.But this is unassigned.
For example:
```C++
CChartCtrl chart;
ASSERT(chart.GetAxis(CChartCtrl::BottomAxis) == NULL);
```
Visual Studio Version:17.10.4
ChartCtrl is from https://github.com/WaitFoF/ChartDemo/tree/master/ChartCtrl

**Comment by scottgshin** [comment]
This issue is not for this project. You are referencing a file from WaitFoF's project not his one. m_pAx

ChartCtrl is from https://github.com/WaitFoF/ChartDemo/tree/master/ChartCtrl
