### ISSUE TITLE
Visual Studio 2022 Not working

### ISSUE THREAD

**Issue by ElectroFuzz** [scottgshin/ChartCtrl#7]
The lib and the demo project compile but the application crashes when it starts.
![Screenshot 2023-05-08 230843](https://user-images.githubusercontent.com/7026571/236949118-cedf4955-fee7-49d1-888a-f11c15edd429.png)
![Screenshot 2023-05-08 233758](https://user-images.githubusercontent.com/7026571/236952839-0f8f2c8a-e3f7-4f05-8e2a-a57af7338adc.png)

**Comment by scottgshin** [comment]
Issue corrected with the fix-demo-exception update.
